# Generated by Django 5.2.12 on 2026-03-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommercialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('기준_년분기_코드', models.IntegerField()),
                ('행정동코드', models.BigIntegerField()),
                ('행정동명', models.CharField(max_length=50)),
                ('통합카테고리', models.CharField(max_length=50)),
                ('당월매출합', models.BigIntegerField()),
                ('매출_20대합', models.BigIntegerField()),
                ('행정동_전체매출', models.BigIntegerField()),
                ('총유동인구', models.BigIntegerField()),
                ('유동_20대', models.BigIntegerField()),
                ('점포수', models.IntegerField()),
                ('행정동_전체점포수', models.IntegerField()),
                ('업종_점포당매출', models.FloatField()),
                ('업종_매출점유율', models.FloatField()),
                ('업종_포화도', models.FloatField()),
                ('경쟁강도', models.FloatField()),
                ('매출_20대비율', models.FloatField()),
                ('유동_20대비율', models.FloatField()),
                ('MZ_차이', models.FloatField()),
                ('유동대비매출', models.FloatField()),
                ('점포대비유동', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['행정동명'], name='analysis_co_행정동명_b26457_idx'), models.Index(fields=['행정동명', '통합카테고리'], name='analysis_co_행정동명_d32cd6_idx')],
            },
        ),
    ]
