# Generated by Django 5.2.11 on 2026-03-11 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('상가업소번호', models.CharField(max_length=30, unique=True)),
                ('상호명', models.CharField(max_length=100)),
                ('통합카테고리', models.CharField(max_length=50)),
                ('상권업종소분류명', models.CharField(max_length=100)),
                ('행정동명', models.CharField(max_length=50)),
                ('도로명주소', models.CharField(blank=True, max_length=200)),
                ('위도', models.FloatField()),
                ('경도', models.FloatField()),
                ('기준_년분기_코드', models.IntegerField()),
            ],
            options={
                'indexes': [models.Index(fields=['행정동명'], name='analysis_st_행정동명_3ff348_idx'), models.Index(fields=['행정동명', '통합카테고리'], name='analysis_st_행정동명_644b96_idx')],
            },
        ),
    ]
