# Generated by Django 5.2.11 on 2026-03-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_storeinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialdata',
            name='개업_율_평균',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='주거인구',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='직장_20대_비율',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='직장_20대_인구',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='총_직장_인구_수',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='폐업_률_평균',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='프랜차이즈_점포수',
            field=models.IntegerField(null=True),
        ),
    ]
