# Generated by Django 5.2.11 on 2026-03-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_commercialdata_개업_율_평균_commercialdata_주거인구_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('행정동명', models.CharField(max_length=50)),
                ('통합카테고리', models.CharField(max_length=50)),
                ('기준_년분기_코드', models.IntegerField()),
                ('성장확률', models.FloatField()),
                ('업종내_순위', models.IntegerField()),
                ('업종내_전체동수', models.IntegerField()),
                ('상위_퍼센트', models.FloatField()),
                ('등급', models.CharField(max_length=2)),
            ],
            options={
                'indexes': [models.Index(fields=['행정동명'], name='analysis_sc_행정동명_a7a63f_idx'), models.Index(fields=['행정동명', '통합카테고리'], name='analysis_sc_행정동명_87a441_idx')],
            },
        ),
    ]
