# Generated by Django 5.2.11 on 2026-03-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0004_scoredata'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commercialdata',
            index=models.Index(fields=['행정동명', '기준_년분기_코드'], name='analysis_co_행정동명_d97fed_idx'),
        ),
        migrations.AddIndex(
            model_name='commercialdata',
            index=models.Index(fields=['기준_년분기_코드'], name='analysis_co_기준_년분기__ca7168_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinfo',
            index=models.Index(fields=['행정동명', '기준_년분기_코드'], name='analysis_st_행정동명_a0ddef_idx'),
        ),
    ]
