# Generated by Django 5.2.11 on 2026-03-21 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0005_commercialdata_analysis_co_행정동명_d97fed_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialdata',
            name='남성매출합',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='매출_남성비율',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='매출_여성비율',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='매출_주말비율',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='시간대_00_06_매출',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='시간대_06_11_매출',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='시간대_11_14_매출',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='시간대_14_17_매출',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='시간대_17_21_매출',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='시간대_21_24_매출',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='여성매출합',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='주말매출합',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='commercialdata',
            name='주중매출합',
            field=models.BigIntegerField(null=True),
        ),
    ]
