# Generated by Django 5.2.11 on 2026-03-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0006_commercialdata_남성매출합_commercialdata_매출_남성비율_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetCommercialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('기준_년분기_코드', models.IntegerField()),
                ('상권_코드', models.BigIntegerField()),
                ('상권_코드_명', models.CharField(max_length=100)),
                ('통합카테고리', models.CharField(max_length=50)),
                ('당월_매출_금액', models.BigIntegerField()),
                ('당월_매출_건수', models.BigIntegerField()),
                ('객단가', models.FloatField(null=True)),
                ('매출_증감률', models.FloatField(null=True)),
                ('매출_주말비율', models.FloatField(null=True)),
                ('매출_저녁비율', models.FloatField(null=True)),
                ('총_유동인구_수', models.BigIntegerField(null=True)),
                ('유동_증감률', models.FloatField(null=True)),
                ('월_평균_소득_금액', models.FloatField(null=True)),
                ('지출_총금액', models.FloatField(null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['상권_코드'], name='analysis_st_상권_코드_99f789_idx'), models.Index(fields=['상권_코드', '통합카테고리'], name='analysis_st_상권_코드_a72a59_idx'), models.Index(fields=['통합카테고리'], name='analysis_st_통합카테고리_e7e780_idx')],
            },
        ),
        migrations.CreateModel(
            name='StreetScoreData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('상권_코드', models.BigIntegerField()),
                ('상권_코드_명', models.CharField(max_length=100)),
                ('통합카테고리', models.CharField(max_length=50)),
                ('기준_년분기_코드', models.IntegerField()),
                ('성장확률', models.FloatField()),
                ('업종내_순위', models.IntegerField()),
                ('업종내_전체상권수', models.IntegerField()),
                ('상위_퍼센트', models.FloatField()),
                ('등급', models.CharField(max_length=2)),
            ],
            options={
                'indexes': [models.Index(fields=['상권_코드'], name='analysis_st_상권_코드_a9ba3e_idx'), models.Index(fields=['상권_코드', '통합카테고리'], name='analysis_st_상권_코드_deba9d_idx'), models.Index(fields=['통합카테고리'], name='analysis_st_통합카테고리_1f08e7_idx')],
            },
        ),
    ]
