# Generated by Django 5.2.11 on 2026-04-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0008_commercialdata_금요일매출합_commercialdata_금요일유동_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeinfo',
            name='상가업소번호',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='storeinfo',
            unique_together={('상가업소번호', '기준_년분기_코드')},
        ),
        migrations.AddIndex(
            model_name='storeinfo',
            index=models.Index(fields=['상권업종소분류명'], name='analysis_st_상권업종소분류_0f301d_idx'),
        ),
        migrations.AddIndex(
            model_name='storeinfo',
            index=models.Index(fields=['행정동명', '상권업종소분류명'], name='analysis_st_행정동명_74522d_idx'),
        ),
    ]
