# Generated by Django 5.2.11 on 2026-04-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.TextField(blank=True, default=''),
        ),
    ]
