# Generated by Django 5.2.11 on 2026-04-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='board',
            field=models.CharField(choices=[('free', '자유게시판'), ('info', '정보게시판'), ('notice', '공지게시판')], max_length=10),
        ),
    ]
